version: "3"
services:
  go-server:
    build:
      dockerfile: Dockerfile
      context: ./go
    ports:
      - 8000:8000
  python-server:
    build:
      dockerfile: Dockerfile
      context: ./python
    ports:
      - 8001:8001
  ruby-server:
    build:
      dockerfile: Dockerfile
      context: ./ruby
    ports:
      - 8002:8002
